### ISSUE TITLE
Buffer for In Combat function

### ISSUE THREAD

**Issue by Krabator** [querns/buff-cap#14]
Hello,

Is it possible to add the buffer feature in the "In Combat" part of your addon ?
For the moment your /click BCT acts like a "buffer 32" "Out of Combat" parameterization.

I would like the /click BCT to act like the "Out of combat" part if a buffer is specified !

Example : 
I have specified buffer = 2
A renew (blacklisted buff) is launched on my character during a fight (so we are in combat)

If I have 29 buff, when click BCT is called, nothing happen
If I have 31 buff, when click BCT is called, all the blacklisted buff are wiped

**Comment by querns** [comment]
This repository isn't for a WoW Classic addon. It's for a website that helps you plan your buff cap allowances in advance. I'm not sure which addon you're referencing, but I'd try and find their Github repository or Discord room or whatever.

**Comment by Krabator** [comment]
I refer to this addon : https://www.curseforge.com/wow/addons/buff-cap-tracker-classic
