### ISSUE TITLE
Arcane Might & MC

### ISSUE THREAD

**Issue by d07RiV** [querns/buff-cap#15]
As mentioned in the popup, I tried mind controlling the NPC. Typing out "/cast Arcane Might" (or using a macro) doesn't work, and there is no pet tab in spellbook for priests.

https://gfycat.com/anycircularduiker

![image](https://user-images.githubusercontent.com/3448203/82917061-8fc3f780-9f7b-11ea-8c16-9076e2d99021.png)

**Comment by querns** [comment]
Thanks for the legwork! I appreciate it. I assume you are Rivx on Razorgore (EU)? Just so I can give you proper credit.

**Comment by d07RiV** [comment]
Aye, thanks.
