### ISSUE TITLE
Add arcanums to buff cap

### ISSUE THREAD

**Issue by dleblond312** [querns/buff-cap#16]
According to blue post from Blizzard, arcanums **do** count towards cap, it's unclear if ZG counts as well.

https://us.forums.blizzard.com/en/wow/t/buff-cap-and-hidden-auras/297178/89

Can we get these added to the calculator?

**Comment by querns** [comment]
This post is from October of 2019. Independent testing of the arcanums and ZG idol enchants were performed by an individual in FC, and neither were found to contribute to the buff cap after the [change a month ago.](https://us.forums.blizzard.com/en/wow/t/enchantment-bugs-and-buff-slots/507027)
