### ISSUE TITLE
[Request] Hunter buffs

### ISSUE THREAD

**Issue by danika** [querns/buff-cap#2]
I believe Rapid Fire and Quick Shots procs from Improved Aspect of the Hawk count towards the cap. I'd also imagine that since the warlock T1/T2 5-set bonus seems to count towards the cap, the hunter T1/T2 5-set bonuses would also count, but I haven't tested this personally yet.

**Comment by querns** [comment]
Thank you for submitting this list. I've added these buffs and some others I found sifting through Wowhead.
