### ISSUE TITLE
Poison's not included 

### ISSUE THREAD

**Issue by mekaj** [querns/buff-cap#24]
Thanks for the great tool! as of right now there's no way to include 1-2 poison buffs for rogues. 

Thanks
Astraea on Pagle

**Comment by querns** [comment]
Do poisons consume a buff slot? My understanding is that weapon imbues like Windfury, poisons, and elemental sharpening stones don't actually consume a buff. The only reason Windfury is on the list is because when Windfury procs, it gives you a buff to increase the attack power of your next hit.

**Comment by querns** [comment]
This ticket is three weeks old, and no new information is forthcoming. If you've got any evidence to suggest that poisons consume a buff slot, feel free to open a new ticket, comment on this one, or whatever.
