### ISSUE TITLE
rogue buffs

### ISSUE THREAD

**Issue by zenots** [querns/buff-cap#3]
Pretty sure Vanish takes up 2-3 buff slots. Stealth + Immunity + cleanse

https://classicdb.ch/?spell=1857

Stealth + Purge + "sanctuary" Is what the db is showing.

**Comment by querns** [comment]
Is classicdb.ch a reliable source of information about WoW Classic? I was never sure if it represented classic, or a particular pserver. If it is, then I can make vanish count as 3 buffs, no problem.

**Comment by zenots** [comment]
I wouldn't say classicdb is exceptionally reliable, and I don't play a rogue myself to test it but given how everything else in classic works I'd be surprised if it doesn't work this way what with defensive state and everything, a hidden buff for the immune and purge is very believable and pservers didn't even have to deal with this level of buffcap crap. Obviously it would be best if we can get a rogue to actually test it. Given how many spots it supposedly takes it should be pretty easy to notice lol.

**Comment by querns** [comment]
I did some community outreach to the Classic Rogue discord, and no one I talked to seemed to believe that Vanish used more than two buffs. Given that stealth is already listed as a buff, as well as Vanish's improved stealth effect being present, I feel that the calculator can adequately represent Vanish's effect on your buff cap. As such, I'm going to mark this closed. If you or anyone else can find compelling, reproducible evidence that Vanish consumes a third buff, please make a new ticket.
