### ISSUE TITLE
Change Alcohol Buff from singular to multiple possible

### ISSUE THREAD

**Issue by SaschaErcevic** [querns/buff-cap#32]
Hey,

was using your bufftracker and realized that it only allows to check if you have an alcohol buff from dire maul or not, but in reality you can have both of these, which especially healers often do. 
Would be nice if you could add the same functionality you have on elixirs or classbuffs to alcohol. 

Here is an ingame screenshot of me having both beers for reference: https://i.imgur.com/aFoZStN.png

Kind regards,
A beer loving Healer

**Comment by querns** [comment]
Thanks for the report. I had tested Rumsey Rum and the Gordok alcohol, but neglected to buy the spirit alcohol. You should now be able to stack the spirit and stamina alcohols in the calculator.
