### ISSUE TITLE
Mage Buffs

### ISSUE THREAD

**Issue by AmNegative** [querns/buff-cap#4]
Website is currently missing mage personal buffs as well as food/drink. 

Blink
Clearcasting
Arcane Power
Mage/Ice Armor
Combustion
Presence of Mind
Ice Barrier
Mana Shield
Fire/Frost Ward

**Comment by querns** [comment]
Added these personal buffs, buffs for consuming food/drink, and Ice Block in [this commit](https://github.com/querns/buff-cap/commit/e3c39e1f7fb3f00528e53b5c5e31beea614f42dd). Thanks for your help!
